/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'vajra-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.android-arm64.node')
          } else {
            nativeBinding = require('vajra-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'vajra-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('vajra-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'vajra-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('vajra-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'vajra-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('vajra-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vajra-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('vajra-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'vajra-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vajra-native.darwin-universal.node')
      } else {
        nativeBinding = require('vajra-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'vajra-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.darwin-x64.node')
          } else {
            nativeBinding = require('vajra-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vajra-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.darwin-arm64.node')
          } else {
            nativeBinding = require('vajra-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'vajra-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vajra-native.freebsd-x64.node')
      } else {
        nativeBinding = require('vajra-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('vajra-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('vajra-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('vajra-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('vajra-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('vajra-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('vajra-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('vajra-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vajra-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vajra-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('vajra-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'vajra-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vajra-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('vajra-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { getEnv, envExists, getAllEnv, getEnvFiltered, currentDir, setCurrentDir, homeDir, tempDir, parseEnv, loadEnvFile, renderSampleEnv, ensureSampleEnv, readFile, writeFile, editFile, deleteFile, deleteDir, createDir, listFiles, fileExists, isFile, isDir, copyFile, renameFile, fileSize, readFileAsync, writeFileAsync, listFilesAsync, resolvePath, normalizePath, realPath, joinPaths, dirname, basename, extension, isAbsolute, pathExists, parentPath, ensureExt, defaultPermissions, loadPermissions, savePermissions, permissionsFor, scanProject, runCommand, runShell, runCommandAsync, runShellAsync, which, redact, minRedactableLength, version } = nativeBinding

module.exports.getEnv = getEnv
module.exports.envExists = envExists
module.exports.getAllEnv = getAllEnv
module.exports.getEnvFiltered = getEnvFiltered
module.exports.currentDir = currentDir
module.exports.setCurrentDir = setCurrentDir
module.exports.homeDir = homeDir
module.exports.tempDir = tempDir
module.exports.parseEnv = parseEnv
module.exports.loadEnvFile = loadEnvFile
module.exports.renderSampleEnv = renderSampleEnv
module.exports.ensureSampleEnv = ensureSampleEnv
module.exports.readFile = readFile
module.exports.writeFile = writeFile
module.exports.editFile = editFile
module.exports.deleteFile = deleteFile
module.exports.deleteDir = deleteDir
module.exports.createDir = createDir
module.exports.listFiles = listFiles
module.exports.fileExists = fileExists
module.exports.isFile = isFile
module.exports.isDir = isDir
module.exports.copyFile = copyFile
module.exports.renameFile = renameFile
module.exports.fileSize = fileSize
module.exports.readFileAsync = readFileAsync
module.exports.writeFileAsync = writeFileAsync
module.exports.listFilesAsync = listFilesAsync
module.exports.resolvePath = resolvePath
module.exports.normalizePath = normalizePath
module.exports.realPath = realPath
module.exports.joinPaths = joinPaths
module.exports.dirname = dirname
module.exports.basename = basename
module.exports.extension = extension
module.exports.isAbsolute = isAbsolute
module.exports.pathExists = pathExists
module.exports.parentPath = parentPath
module.exports.ensureExt = ensureExt
module.exports.defaultPermissions = defaultPermissions
module.exports.loadPermissions = loadPermissions
module.exports.savePermissions = savePermissions
module.exports.permissionsFor = permissionsFor
module.exports.scanProject = scanProject
module.exports.runCommand = runCommand
module.exports.runShell = runShell
module.exports.runCommandAsync = runCommandAsync
module.exports.runShellAsync = runShellAsync
module.exports.which = which
module.exports.redact = redact
module.exports.minRedactableLength = minRedactableLength
module.exports.version = version
