/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EnvVar {
  key: string
  value: string
}
export declare function getEnv(key: string): string | null
export declare function envExists(key: string): boolean
export declare function getAllEnv(): Array<EnvVar>
export declare function getEnvFiltered(prefix: string): Array<EnvVar>
export declare function currentDir(): string
/**
 * Change the process working directory.
 *
 * This is process-global and affects every thread, including Node's. Prefer
 * passing `cwd` to `runCommand`/`runShell` over changing it here.
 */
export declare function setCurrentDir(path: string): void
export declare function homeDir(): string | null
export declare function tempDir(): string
export declare function readFile(path: string): string
export declare function writeFile(path: string, content: string): void
/**
 * Replace `old_string` with `new_string` in a file.
 *
 * Fails when `old_string` is absent, and — unless `replace_all` is set — when it
 * occurs more than once. An ambiguous match is a caller bug: silently rewriting
 * every occurrence is how an edit intended for one call site corrupts a file.
 * Returns the number of replacements made.
 */
export declare function editFile(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): number
/**
 * Delete a single file. Errors if the path is a directory — use `deleteDir` for
 * that, so a recursive tree removal is always an explicit choice at the call site.
 */
export declare function deleteFile(path: string): void
/**
 * Delete a directory. Non-recursive by default, so it fails on a non-empty
 * directory rather than destroying its contents.
 */
export declare function deleteDir(path: string, recursive?: boolean | undefined | null): void
export declare function createDir(path: string): void
export interface FileEntry {
  name: string
  path: string
  isFile: boolean
  isDir: boolean
  isSymlink: boolean
  size: number
}
/**
 * List directory contents, optionally recursing.
 *
 * Symlinks are reported but never followed, and depth is capped at `MAX_DEPTH`.
 * Both matter: a symlink pointing at one of its own ancestors would otherwise
 * recurse until the stack overflows.
 */
export declare function listFiles(path: string, recursive?: boolean | undefined | null): Array<FileEntry>
export declare function fileExists(path: string): boolean
export declare function isFile(path: string): boolean
export declare function isDir(path: string): boolean
export declare function copyFile(source: string, destination: string): void
export declare function renameFile(source: string, destination: string): void
export declare function fileSize(path: string): number
/**
 * Make a path absolute against the current working directory and normalize it.
 * Does not require the path to exist.
 */
export declare function resolvePath(path: string): string
/** Lexically normalize a path. Works whether or not the path exists. */
export declare function normalizePath(path: string): string
/**
 * Canonicalize a path via the filesystem, resolving symlinks.
 * The path must exist.
 */
export declare function realPath(path: string): string
export declare function joinPaths(base: string, relative: string): string
export declare function dirname(path: string): string | null
export declare function basename(path: string, ext?: string | undefined | null): string | null
export declare function extension(path: string): string | null
export declare function isAbsolute(path: string): boolean
export declare function pathExists(path: string): boolean
export declare function parentPath(path: string): string | null
/** Append `ext` unless the path already has an extension. */
export declare function ensureExt(path: string, ext: string): string
export interface CommandResult {
  stdout: string
  stderr: string
  /** Exit code, or -1 when the process was terminated by a signal. */
  code: number
}
/**
 * Run a program directly, without a shell. Arguments are passed through
 * verbatim, so no quoting or escaping is applied to them.
 */
export declare function runCommand(command: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): CommandResult
/**
 * Run a command through the platform shell.
 *
 * The string is interpreted by the shell, so anything interpolated into it is
 * executed as code. Prefer `runCommand` for anything built from untrusted input.
 */
export declare function runShell(command: string, cwd?: string | undefined | null): CommandResult
/**
 * Locate an executable on PATH, returning its full path.
 *
 * This searches PATH directly rather than shelling out to `which`/`where`:
 * no subprocess, and it avoids the trap that `where` prints *every* match on
 * separate lines, so treating its whole output as one path is wrong.
 */
export declare function which(command: string): string | null
export declare function version(): string
