/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EnvVar {
  key: string
  value: string
}
export declare function getEnv(key: string): string | null
export declare function envExists(key: string): boolean
export declare function getAllEnv(): Array<EnvVar>
export declare function getEnvFiltered(prefix: string): Array<EnvVar>
export declare function currentDir(): string
/**
 * Change the process working directory.
 *
 * This is process-global and affects every thread, including Node's. Prefer
 * passing `cwd` to `runCommand`/`runShell` over changing it here.
 */
export declare function setCurrentDir(path: string): void
export declare function homeDir(): string | null
export declare function tempDir(): string
export declare function parseEnv(content: string): Array<EnvVar>
export declare function loadEnvFile(path: string): Array<EnvVar>
export declare function renderSampleEnv(content: string): string
/**
 * Write the sample file if it does not exist yet. Returns true if it created one.
 *
 * Deliberately refuses to overwrite: the sample may have been edited by hand,
 * and clobbering it on every run would discard that.
 */
export declare function ensureSampleEnv(original: string, sample: string): boolean
export declare function readFile(path: string): string
export declare function writeFile(path: string, content: string): void
/**
 * Replace `old_string` with `new_string` in a file.
 *
 * Fails when `old_string` is absent, and — unless `replace_all` is set — when it
 * occurs more than once. An ambiguous match is a caller bug: silently rewriting
 * every occurrence is how an edit intended for one call site corrupts a file.
 * Returns the number of replacements made.
 */
export declare function editFile(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): number
/**
 * Delete a single file. Errors if the path is a directory — use `deleteDir` for
 * that, so a recursive tree removal is always an explicit choice at the call site.
 */
export declare function deleteFile(path: string): void
/**
 * Delete a directory. Non-recursive by default, so it fails on a non-empty
 * directory rather than destroying its contents.
 */
export declare function deleteDir(path: string, recursive?: boolean | undefined | null): void
/**
 * Create a directory, creating any missing parents. Idempotent: succeeds
 * silently if the directory already exists, rather than treating that as an
 * error the way a bare `mkdir` would.
 */
export declare function createDir(path: string): void
export interface FileEntry {
  name: string
  path: string
  isFile: boolean
  isDir: boolean
  isSymlink: boolean
  size: number
}
/**
 * List directory contents, optionally recursing.
 *
 * Symlinks are reported but never followed, and depth is capped at `MAX_DEPTH`.
 * Both matter: a symlink pointing at one of its own ancestors would otherwise
 * recurse until the stack overflows.
 */
export declare function listFiles(path: string, recursive?: boolean | undefined | null): Array<FileEntry>
export declare function fileExists(path: string): boolean
export declare function isFile(path: string): boolean
export declare function isDir(path: string): boolean
/**
 * Copy a file. Refuses when `destination` already exists unless `overwrite`
 * is set — `fs::copy` replaces silently by default, which is exactly the kind
 * of surprise `editFile` and `deleteFile` already refuse elsewhere in this
 * module.
 */
export declare function copyFile(source: string, destination: string, overwrite?: boolean | undefined | null): void
/**
 * Rename (move) a file. Refuses when `destination` already exists unless
 * `overwrite` is set.
 *
 * This matters more than the same guard on `copyFile`: `std::fs::rename`
 * delegates to the OS, and POSIX and Windows have historically differed on
 * whether an existing destination is silently replaced or the call fails.
 * Checking explicitly here means the behavior is this function's choice, not
 * whatever the underlying platform happens to do.
 */
export declare function renameFile(source: string, destination: string, overwrite?: boolean | undefined | null): void
export declare function fileSize(path: string): number
export declare function readFileAsync(path: string): Promise<string>
export declare function writeFileAsync(path: string, content: string): Promise<void>
export declare function copyFileAsync(source: string, destination: string, overwrite?: boolean | undefined | null): Promise<void>
export declare function listFilesAsync(path: string, recursive?: boolean | undefined | null): Promise<Array<FileEntry>>
/**
 * Make a path absolute against the current working directory and normalize it.
 * Does not require the path to exist.
 */
export declare function resolvePath(path: string): string
/** Lexically normalize a path. Works whether or not the path exists. */
export declare function normalizePath(path: string): string
/**
 * Canonicalize a path via the filesystem, resolving symlinks.
 * The path must exist.
 */
export declare function realPath(path: string): string
export declare function joinPaths(base: string, relative: string): string
export declare function dirname(path: string): string | null
export declare function basename(path: string, ext?: string | undefined | null): string | null
export declare function extension(path: string): string | null
export declare function isAbsolute(path: string): boolean
export declare function pathExists(path: string): boolean
export declare function parentPath(path: string): string | null
/** Append `ext` unless the path already has an extension. */
export declare function ensureExt(path: string, ext: string): string
export interface FilePermissions {
  read: boolean
  write: boolean
  edit: boolean
  delete: boolean
}
export interface PermissionsConfig {
  version: number
  /** Applied to any path without an entry in `files`. */
  default: FilePermissions
  /** Per-path overrides, keyed by project-relative path with `/` separators. */
  files: Record<string, FilePermissions>
}
export interface ProjectFileEntry {
  name: string
  /**
   * Project-relative, always `/`-separated so a config written on one
   * platform still resolves on another.
   */
  path: string
  isDir: boolean
  /** True for env files whose contents the agent must not see. */
  isMasked: boolean
}
export declare function defaultPermissions(): PermissionsConfig
/**
 * Load `.vajra-perms.json` from a project. Returns null when absent or
 * unparseable, so a corrupt file falls back to the safe default rather than
 * failing the caller.
 */
export declare function loadPermissions(projectDir: string): PermissionsConfig | null
export declare function savePermissions(projectDir: string, config: PermissionsConfig): void
/**
 * Resolve the effective permissions for a project-relative path.
 *
 * Takes the config by value: napi object types cross the boundary as data, not
 * as a reference to a live JS object.
 */
export declare function permissionsFor(config: PermissionsConfig, path: string): FilePermissions
/**
 * List the project's files as permission targets.
 *
 * Returns a flat list rather than a nested tree: it keeps the binding free of
 * a self-referential type, and a caller that wants a tree can rebuild one from
 * the relative paths.
 *
 * Skips `.git`, `node_modules` and `target`, and hidden files other than
 * `.sample.env`. Symlinks are never followed and depth is capped, for the same
 * reason as `file::list_files` — a link to an ancestor would otherwise recurse
 * without end.
 */
export declare function scanProject(projectDir: string): Array<ProjectFileEntry>
export interface CommandResult {
  stdout: string
  stderr: string
  /** Exit code, or -1 when the process was terminated by a signal. */
  code: number
}
/**
 * Run a program directly, without a shell. Arguments are passed through
 * verbatim, so no quoting or escaping is applied to them.
 */
export declare function runCommand(command: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): CommandResult
/**
 * Run a command through the platform shell.
 *
 * The string is interpreted by the shell, so anything interpolated into it is
 * executed as code. Prefer `runCommand` for anything built from untrusted input.
 */
export declare function runShell(command: string, cwd?: string | undefined | null): CommandResult
export declare function runCommandAsync(command: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): Promise<CommandResult>
export declare function runShellAsync(command: string, cwd?: string | undefined | null): Promise<CommandResult>
/**
 * Locate an executable on PATH, returning its full path.
 *
 * This searches PATH directly rather than shelling out to `which`/`where`:
 * no subprocess, and it avoids the trap that `where` prints *every* match on
 * separate lines, so treating its whole output as one path is wrong.
 */
export declare function which(command: string): string | null
/**
 * How well this platform can confine the filesystem.
 *
 * `enforced` — the kernel denies access outside the policy.
 * `partial`  — enforced, but an older kernel cannot honour every restriction.
 * `unsupported` — nothing is enforced. Not a degraded mode: no confinement.
 */
export interface SandboxCapabilities {
  platform: string
  filesystem: string
  /** `landlock`, `seatbelt`, or `none`. */
  mechanism: string
  details: string
  /** Landlock ABI version, when the mechanism is Landlock. */
  abi?: number
}
export interface SandboxConfig {
  projectDir: string
  /** Extra paths granted read+execute — toolchains, interpreters. */
  readExecutePaths?: Array<string>
  /**
   * Extra paths granted read+write without execute — agent state, logs,
   * tokens. These hold data, not binaries.
   */
  readWritePaths?: Array<string>
  /** Per-file permissions. When absent the whole project is read-write. */
  permissions?: PermissionsConfig
  /**
   * Proceed on a platform that cannot enforce anything.
   *
   * Without this, `applySandbox` fails on such a platform rather than
   * returning a success that implies confinement it did not apply.
   */
  allowUnenforced?: boolean
}
export interface SandboxResult {
  /**
   * Whether the kernel is now actually enforcing a policy. False only when
   * the caller opted in via `allowUnenforced`.
   */
  enforced: boolean
  mechanism: string
  /**
   * Anything the caller should surface: an unenforceable restriction on an
   * old kernel, a system path that could not be added, or the fact that
   * nothing was enforced at all.
   */
  warnings: Array<string>
}
/** What this platform can enforce. Safe to call at any time; changes nothing. */
export declare function sandboxCapabilities(): SandboxCapabilities
/**
 * Confine the **current process** to the given policy.
 *
 * This is irreversible and process-wide: it applies to this Node process and
 * every child it spawns afterwards, and cannot be lifted. Call it immediately
 * before handing control to the agent, never speculatively — once applied, the
 * harness itself is subject to it too.
 *
 * Fails on a platform with no enforcement unless `allowUnenforced` is set, so
 * the unconfined case has to be chosen rather than stumbled into.
 */
export declare function applySandbox(config: SandboxConfig): SandboxResult
/**
 * Replace every occurrence of each secret value with `[REDACTED:<KEY>]`.
 *
 * When streaming process output, redact whole lines rather than raw read
 * chunks: a secret split across two chunk boundaries would otherwise slip
 * through unmatched.
 */
export declare function redact(text: string, secrets: Array<EnvVar>): string
/**
 * The shortest secret value that `redact` will act on. Exposed so a caller can
 * warn that a given variable will not be scrubbed, rather than assuming it was.
 */
export declare function minRedactableLength(): number
export declare function version(): string
