/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EnvVar {
  key: string
  value: string
}
export declare function getEnv(key: string): string | null
export declare function envExists(key: string): boolean
export declare function getAllEnv(): Array<EnvVar>
export declare function getEnvFiltered(prefix: string): Array<EnvVar>
export declare function currentDir(): string
/**
 * Change the process working directory.
 *
 * This is process-global and affects every thread, including Node's. Prefer
 * passing `cwd` to `runCommand`/`runShell` over changing it here.
 */
export declare function setCurrentDir(path: string): void
export declare function homeDir(): string | null
export declare function tempDir(): string
export declare function parseEnv(content: string): Array<EnvVar>
export declare function loadEnvFile(path: string): Array<EnvVar>
export declare function renderSampleEnv(content: string): string
/** Write the sample file if it does not exist yet. Returns true if it created one. */
export declare function ensureSampleEnv(original: string, sample: string): boolean
export declare function readFileAsync(path: string): Promise<string>
export declare function writeFileAsync(path: string, content: string): Promise<void>
export declare function copyFileAsync(source: string, destination: string, overwrite?: boolean | undefined | null): Promise<void>
export declare function listFilesAsync(path: string, recursive?: boolean | undefined | null): Promise<Array<FileEntry>>
export declare function readFile(path: string): string
export declare function writeFile(path: string, content: string): void
/**
 * Returns the number of replacements made. Fails when `old_string` is absent
 * or occurs more than once (unless `replace_all` is set).
 */
export declare function editFile(path: string, oldString: string, newString: string, replaceAll?: boolean | undefined | null): number
/** Errors if the path is a directory — use `delete_dir` instead. */
export declare function deleteFile(path: string): void
/** Non-recursive by default — fails on non-empty directories. */
export declare function deleteDir(path: string, recursive?: boolean | undefined | null): void
/** Creates missing parents. Idempotent. */
export declare function createDir(path: string): void
export interface FileEntry {
  name: string
  path: string
  isFile: boolean
  isDir: boolean
  isSymlink: boolean
  size: number
}
/** Symlinks are reported but never followed; depth capped at `MAX_DEPTH`. */
export declare function listFiles(path: string, recursive?: boolean | undefined | null): Array<FileEntry>
export declare function fileExists(path: string): boolean
export declare function isFile(path: string): boolean
export declare function isDir(path: string): boolean
/** Refuses to overwrite `destination` unless `overwrite` is set. */
export declare function copyFile(source: string, destination: string, overwrite?: boolean | undefined | null): void
/** Refuses to overwrite `destination` unless `overwrite` is set. */
export declare function renameFile(source: string, destination: string, overwrite?: boolean | undefined | null): void
export declare function fileSize(path: string): number
/**
 * Make a path absolute against the current working directory and normalize it.
 * Does not require the path to exist.
 */
export declare function resolvePath(path: string): string
/** Lexically normalize a path. Works whether or not the path exists. */
export declare function normalizePath(path: string): string
/**
 * Canonicalize a path via the filesystem, resolving symlinks.
 * The path must exist.
 */
export declare function realPath(path: string): string
export declare function joinPaths(base: string, relative: string): string
export declare function dirname(path: string): string | null
export declare function basename(path: string, ext?: string | undefined | null): string | null
export declare function extension(path: string): string | null
export declare function isAbsolute(path: string): boolean
export declare function pathExists(path: string): boolean
export declare function parentPath(path: string): string | null
/** Append `ext` unless the path already has an extension. */
export declare function ensureExt(path: string, ext: string): string
export interface FilePermissions {
  read: boolean
  write: boolean
  edit: boolean
  delete: boolean
}
export interface PermissionsConfig {
  version: number
  default: FilePermissions
  files: Record<string, FilePermissions>
}
export interface ProjectFileEntry {
  name: string
  path: string
  isDir: boolean
  isMasked: boolean
}
export declare function defaultPermissions(): PermissionsConfig
export declare function loadPermissions(projectDir: string): PermissionsConfig | null
export declare function savePermissions(projectDir: string, config: PermissionsConfig): void
export declare function permissionsFor(config: PermissionsConfig, path: string): FilePermissions
export declare function scanProject(projectDir: string): Array<ProjectFileEntry>
export interface CommandResult {
  stdout: string
  stderr: string
  /** Exit code, or -1 when the process was terminated by a signal. */
  code: number
}
/** Run a program directly, without a shell. */
export declare function runCommand(command: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): CommandResult
/**
 * Run a command through the platform shell. Prefer `runCommand` for
 * untrusted input — shell interpolation executes as code.
 */
export declare function runShell(command: string, cwd?: string | undefined | null): CommandResult
export declare function runCommandAsync(command: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): Promise<CommandResult>
export declare function runShellAsync(command: string, cwd?: string | undefined | null): Promise<CommandResult>
/** Locate an executable on PATH, returning its full path. */
export declare function which(command: string): string | null
export interface SandboxCapabilities {
  platform: string
  filesystem: string
  mechanism: string
  details: string
  abi?: number
}
export interface SandboxConfig {
  projectDir: string
  readExecutePaths?: Array<string>
  readWritePaths?: Array<string>
  permissions?: PermissionsConfig
  allowUnenforced?: boolean
}
export interface SandboxResult {
  enforced: boolean
  mechanism: string
  warnings: Array<string>
}
export declare function sandboxCapabilities(): SandboxCapabilities
export declare function applySandbox(config: SandboxConfig): SandboxResult
/** Replace every occurrence of each secret value with `[REDACTED:<KEY>]`. */
export declare function redact(text: string, secrets: Array<EnvVar>): string
/**
 * The shortest secret value that `redact` will act on. Exposed so a caller can
 * warn that a given variable will not be scrubbed, rather than assuming it was.
 */
export declare function minRedactableLength(): number
export declare function version(): string
