packages:
  - "."
  - "packages/*"

allowBuilds:
  '@google/genai': set this to true or false
  better-sqlite3: true
  esbuild: true
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
onlyBuiltDependencies:
  - esbuild
