export {
  SESSION_SCHEMA_VERSION,
  LEGACY_SESSION_SCHEMA_VERSION,
  VAJRA_DIR,
  MISSING_FILE_HASH,
  assertSessionId,
  saveSession,
  loadSession,
  latestSession,
  listSessions,
  deleteSession,
  appendMessage,
  loadMessages,
  deriveSessionStatus,
  evidenceToRecord,
  evidenceFromRecord,
  hashFile,
  inspectFile,
  hashContent,
  DIRECTORY_FILE_HASH,
  UNREADABLE_FILE_HASH,
  repoFingerprint,
  loadSummaryIndexCache,
  saveSummaryIndexCache,
  readGitState,
} from './session.js'
export { openDb, closeDb } from './db.js'
export type {
  PersistedSession,
  PersistedTask,
  PersistedEvidence,
  PersistedConfig,
  PersistedMessage,
  SessionPhase,
  SessionSummary,
  EvidenceMaps,
  GitState,
  SummaryIndexCache,
  SummaryIndexCacheEntry,
  FileState,
} from './session.js'
