//! Reading `.env` files and generating the sample that stands in for them.
//!
//! Ported from the legacy CLI (`legacy/src/envfile.rs`). The logic is pure text
//! handling with no platform dependencies, so it carries over unchanged; only
//! the napi bindings and path handling are new.

use crate::env::EnvVar;
use napi::Error;
use std::path::Path;

/// Parse `.env` content into key/value pairs.
///
/// Tolerates comments, blank lines, `export ` prefixes, and quoted values.
/// Lines that are not `KEY=VALUE`, or whose key is not a plain identifier, are
/// skipped rather than treated as an error — a `.env` in the wild routinely
/// contains things this does not model, and refusing the whole file over one
/// odd line would be worse than ignoring it.
pub fn parse(content: &str) -> Vec<(String, String)> {
    let mut vars = Vec::new();

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let line = line.strip_prefix("export ").unwrap_or(line).trim_start();
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };

        let key = key.trim();
        if key.is_empty() || !key.chars().all(|c| c.is_alphanumeric() || c == '_') {
            continue;
        }

        let value = value.trim();
        let value = value
            .strip_prefix('"')
            .and_then(|v| v.strip_suffix('"'))
            .or_else(|| value.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')))
            .unwrap_or(value);

        vars.push((key.to_string(), value.to_string()));
    }

    vars
}

/// Render a sample env file: the same keys as the original, with empty values.
pub fn render_sample(original: &str) -> String {
    let mut out = String::from(
        "# Generated by vajra: variable names available to the app.\n\
         # Values are injected at run time; edit the real env file to change them.\n",
    );

    for (key, _) in parse(original) {
        out.push_str(&key);
        out.push_str("=\n");
    }

    out
}

#[napi]
pub fn parse_env(content: String) -> Vec<EnvVar> {
    parse(&content)
        .into_iter()
        .map(|(key, value)| EnvVar { key, value })
        .collect()
}

#[napi]
pub fn load_env_file(path: String) -> Result<Vec<EnvVar>, Error> {
    let content = std::fs::read_to_string(&path)
        .map_err(|e| Error::from_reason(format!("Failed to read '{}': {}", path, e)))?;
    Ok(parse_env(content))
}

#[napi]
pub fn render_sample_env(content: String) -> String {
    render_sample(&content)
}

/// Write the sample file if it does not exist yet. Returns true if it created one.
///
/// Deliberately refuses to overwrite: the sample may have been edited by hand,
/// and clobbering it on every run would discard that.
#[napi]
pub fn ensure_sample_env(original: String, sample: String) -> Result<bool, Error> {
    let original_path = Path::new(&original);
    let sample_path = Path::new(&sample);

    if sample_path.exists() || !original_path.exists() {
        return Ok(false);
    }

    let content = std::fs::read_to_string(original_path)
        .map_err(|e| Error::from_reason(format!("Failed to read '{}': {}", original, e)))?;

    std::fs::write(sample_path, render_sample(&content))
        .map_err(|e| Error::from_reason(format!("Failed to write '{}': {}", sample, e)))?;

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_basic_pairs() {
        let vars = parse("FOO=bar\nBAZ=qux");
        assert_eq!(
            vars,
            vec![("FOO".into(), "bar".into()), ("BAZ".into(), "qux".into())]
        );
    }

    #[test]
    fn skips_comments_and_blanks() {
        let vars = parse("# comment\n\nFOO=bar\n  # indented comment\n");
        assert_eq!(vars, vec![("FOO".into(), "bar".into())]);
    }

    #[test]
    fn handles_export_prefix_and_quotes() {
        let vars = parse("export FOO=\"bar baz\"\nBAR='single'\n");
        assert_eq!(
            vars,
            vec![
                ("FOO".into(), "bar baz".into()),
                ("BAR".into(), "single".into())
            ]
        );
    }

    #[test]
    fn keeps_equals_in_value_and_rejects_bad_keys() {
        let vars = parse("URL=postgres://u:p@h/db?a=b\nnot a key=x\n=novalue\n");
        assert_eq!(vars, vec![("URL".into(), "postgres://u:p@h/db?a=b".into())]);
    }

    #[test]
    fn sample_has_keys_without_values() {
        let sample = render_sample("SECRET=hunter2\nAPI_KEY=abc\n");
        assert!(sample.contains("SECRET=\n"));
        assert!(sample.contains("API_KEY=\n"));
        assert!(!sample.contains("hunter2"));
        assert!(!sample.contains("abc"));
    }

    #[test]
    fn ensure_sample_does_not_clobber_an_existing_file() {
        let dir = std::env::temp_dir().join(format!("vajra-envfile-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let original = dir.join(".env");
        let sample = dir.join(".sample.env");
        std::fs::write(&original, "SECRET=hunter2\n").unwrap();

        let created = ensure_sample_env(
            original.to_string_lossy().to_string(),
            sample.to_string_lossy().to_string(),
        )
        .unwrap();
        assert!(created);
        assert!(!std::fs::read_to_string(&sample).unwrap().contains("hunter2"));

        std::fs::write(&sample, "HAND_EDITED=\n").unwrap();
        let created_again = ensure_sample_env(
            original.to_string_lossy().to_string(),
            sample.to_string_lossy().to_string(),
        )
        .unwrap();
        assert!(!created_again);
        assert_eq!(std::fs::read_to_string(&sample).unwrap(), "HAND_EDITED=\n");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
