use std::path::Path;

/// Parse a .env file into KEY/VALUE pairs.
/// Tolerates comments, blank lines, `export ` prefixes, and quoted values.
pub fn parse(content: &str) -> Vec<(String, String)> {
    let mut vars = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line).trim_start();
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if key.is_empty() || !key.chars().all(|c| c.is_alphanumeric() || c == '_') {
            continue;
        }
        let value = value.trim();
        let value = value
            .strip_prefix('"')
            .and_then(|v| v.strip_suffix('"'))
            .or_else(|| value.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')))
            .unwrap_or(value);
        vars.push((key.to_string(), value.to_string()));
    }
    vars
}

pub fn load(path: &Path) -> Result<Vec<(String, String)>, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
    Ok(parse(&content))
}

/// Render a sample env file: same keys as the original, empty values.
pub fn render_sample(original: &str) -> String {
    let mut out = String::from(
        "# Generated by vajra: variable names available to the app.\n\
         # Values are injected at run time via `vajra run`; edit the real env file to change them.\n",
    );
    for (key, _) in parse(original) {
        out.push_str(&key);
        out.push_str("=\n");
    }
    out
}

/// Write the sample file if it doesn't exist yet. Returns true if created.
pub fn ensure_sample(original: &Path, sample: &Path) -> Result<bool, String> {
    if sample.exists() || !original.exists() {
        return Ok(false);
    }
    let content = std::fs::read_to_string(original)
        .map_err(|e| format!("Failed to read {}: {}", original.display(), e))?;
    std::fs::write(sample, render_sample(&content))
        .map_err(|e| format!("Failed to write {}: {}", sample.display(), e))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_basic_pairs() {
        let vars = parse("FOO=bar\nBAZ=qux");
        assert_eq!(vars, vec![("FOO".into(), "bar".into()), ("BAZ".into(), "qux".into())]);
    }

    #[test]
    fn skips_comments_and_blanks() {
        let vars = parse("# comment\n\nFOO=bar\n  # indented comment\n");
        assert_eq!(vars, vec![("FOO".into(), "bar".into())]);
    }

    #[test]
    fn handles_export_prefix_and_quotes() {
        let vars = parse("export FOO=\"bar baz\"\nBAR='single'\n");
        assert_eq!(
            vars,
            vec![("FOO".into(), "bar baz".into()), ("BAR".into(), "single".into())]
        );
    }

    #[test]
    fn keeps_equals_in_value_and_rejects_bad_keys() {
        let vars = parse("URL=postgres://u:p@h/db?a=b\nnot a key=x\n=novalue\n");
        assert_eq!(vars, vec![("URL".into(), "postgres://u:p@h/db?a=b".into())]);
    }

    #[test]
    fn sample_has_keys_without_values() {
        let sample = render_sample("SECRET=hunter2\nAPI_KEY=abc\n");
        assert!(sample.contains("SECRET=\n"));
        assert!(sample.contains("API_KEY=\n"));
        assert!(!sample.contains("hunter2"));
        assert!(!sample.contains("abc"));
    }
}
